In [1]:
import numpy as np

#### Create an array of 10 zeros

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an arraay of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of integers from 10 to 50

In [5]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create 3x3 identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use Numpy to generate a arandom number between 1 and 0

In [9]:
np.random.rand(1)

array([0.89581495])

#### Use Numpy to generate an array of 25 random numbers sampled from standard normal distribution

In [10]:
np.random.rand(25)

array([0.26348797, 0.63049736, 0.33837765, 0.81721058, 0.75086332,
       0.11955068, 0.80384507, 0.50696377, 0.9068834 , 0.29655696,
       0.50741528, 0.07069481, 0.73620637, 0.05026315, 0.89498581,
       0.69656346, 0.93532942, 0.66299326, 0.3871439 , 0.05079916,
       0.63266436, 0.91147424, 0.10224915, 0.29759281, 0.00550744])

#### Create matrix

In [11]:
np.linspace(0,1,10)
#np.arange(1,101)/100

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Create an array of 20 linearly spaced points between 0 and 1.

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [13]:
a = np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [14]:
a[2:,1:]
# First for row then comma then second for column

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [15]:
a[1:,2:]

array([[ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])

In [16]:
a[3:4,4:]

array([[20]])

In [17]:
a[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [18]:
a[2,0]

11

In [19]:
a[4]

array([21, 22, 23, 24, 25])

In [20]:
a[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Get the sum of all values in a

In [21]:
a.sum()

325

#### Get the standard deviation of values in a

In [22]:
a.std()

7.211102550927978

#### Get the sum of all columns in a

In [23]:
a.sum(0)

array([55, 60, 65, 70, 75])

#### 1.Create 1D , 2D ,3D numpy array

In [24]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
a = np.arange(1,11).reshape(2,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [26]:
a = np.arange(1,13).reshape(3,2,2)
a

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

#### Print Datatype of array

In [27]:
a.dtype

dtype('int32')

#### Print shape and dimensions of all three different array

In [31]:
np.empty(10)


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

#### Create another 1D array of 12 elements filled with 0

In [28]:
np.linspace(0,0,12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create another 2D array elements filled with ones

In [170]:
np.ones(4).reshape(2,2)

array([[1., 1.],
       [1., 1.]])

#### Create 1D array known as math marks out 0f 100 having 20 elements

In [7]:
b = np.random.randint(1,100,20)
b

array([57, 99, 70, 68,  7, 15, 97, 28, 74, 58, 42, 81, 39, 95,  6, 60, 34,
       51, 32, 68])

#### Sort above array created vertically and horizontally

In [11]:
np.sort(b)

array([ 6,  7, 15, 28, 32, 34, 39, 42, 51, 57, 58, 60, 68, 68, 70, 74, 81,
       95, 97, 99])

In [34]:
rand = np.random.RandomState(42)
rand


RandomState(MT19937) at 0x2273B5B7440

#### Create copy of sorted array to another variable by deep copying.

#### Create 2D array of 5x5 which is indentity matrix and then convert into 1D array 

In [24]:
a = np.eye(5).flatten()
a

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [27]:
a = np.eye(5).reshape(25)
a

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

#### Create 2D array of 3x3.Add one more row to it.

In [19]:
num = np.arange(1,10).reshape(3,3)
num 
#vstack 


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.append(num, [[10,11,12]],axis = 0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

#### Split above array created vertically and horizontally

In [32]:
np.hsplit(num,3)

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [33]:
np.vsplit(num,3)

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

#### Create a 4x4 identity matrix. Add 4 to each element

In [34]:
np.eye(4)+4

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

#### Create 1D array. Initialize with floating point values. Display its ceil,floor and round (with decimal)

In [38]:
arr = np.random.rand(3)
arr

array([0.52527117, 0.7062177 , 0.92269611])

In [39]:
np.ceil(arr)

array([1., 1., 1.])

In [40]:
np.floor(arr)

array([0., 0., 0.])

In [41]:
np.round(arr)

array([1., 1., 1.])

#### Create 5x5 matrix. Display min , max , variance and standard deviation column-wise

In [43]:
arr1 = np.arange(1,26).reshape(5,5)
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
np.max(arr1,axis=0)

array([21, 22, 23, 24, 25])

In [47]:
np.min(arr1,axis=0)

array([1, 2, 3, 4, 5])

In [48]:
np.var(arr1,axis=0)

array([50., 50., 50., 50., 50.])

In [49]:
np.std(arr1,axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

#### Create a null vector of size 10 with 6th value filled with 200

In [56]:
vector = np.zeros(10)
vector[5] = 200
vector

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

#### Create a 1D array/vector with values ranging from 100 to 150 in sequence.

In [64]:
Darray = np.arange(100,151)
Darray

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

#### Reverse above vector

In [65]:
Darray[::-1]

array([150, 149, 148, 147, 146, 145, 144, 143, 142, 141, 140, 139, 138,
       137, 136, 135, 134, 133, 132, 131, 130, 129, 128, 127, 126, 125,
       124, 123, 122, 121, 120, 119, 118, 117, 116, 115, 114, 113, 112,
       111, 110, 109, 108, 107, 106, 105, 104, 103, 102, 101, 100])

#### Create 5x5 matrix with values ranging from 0-24 using some function

In [67]:
Fivearr = np.arange(0,25).reshape(5,5)
Fivearr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### Find indices of nonzero elements from [1,0,2,0,0,4,0,8]

In [73]:
arr = np.array([1,0,2,0,0,4,0,8])
arr2 = np.where(arr != 0)
print(arr2)

(array([0, 2, 5, 7], dtype=int64),)


#### Create 10x10 matrix with 1 on borders and 0 inside

In [6]:
ones = np.ones(100).reshape(10,10)
ones[1:-1,1:-1] = 0
ones.dtype
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### Create 8x8 matrix and fill with 1 and 0 in checkboard pattern

In [106]:
matrix = np.ones(64).reshape(8,8)
matrix[0::2,::2] = 0
matrix[1::2,1::2] = 0
matrix

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### Create two 3x3 matrix with random integer values.Perform matrix addition , multiplication and subtraction

In [100]:
mat1 = np.random.randint(1,10,(3,3))
mat1
mat2 = np.random.randint(1,10,(3,3))
mat1
mat2

array([[2, 1, 1],
       [1, 1, 1],
       [1, 8, 2]])

In [48]:
## matrix of random values and find index of non-zeero values
arr = np.random.randint(0,10,(3,3))
arr


array([[9, 7, 6],
       [8, 3, 0],
       [7, 1, 7]])

In [47]:
arr2 = np.where(arr != 0)
arr2

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [54]:
arr3 = np.random.randn(25).reshape(5,5)
arr3[:,[0,-1]] = np.nan
arr3[[0,-1],:] = np.nan
print(arr3)


[[        nan         nan         nan         nan         nan]
 [        nan -0.45575556  0.71976386  0.78463571         nan]
 [        nan  0.40058425 -0.79165597 -0.15346029         nan]
 [        nan  0.11616801 -0.88819008  0.7227023          nan]
 [        nan         nan         nan         nan         nan]]


In [55]:
arr4 = np.where(arr3 != 0)
arr4

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4], dtype=int64),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4], dtype=int64))